# Generated by Django 3.1.1 on 2020-12-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20201214_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='static/myapp/image/'),
        ),
    ]
